#!/bin/bash

#	LDT - Linux Driver Template
#
#	Test script
#
#	Copyright (C) 2012 Constantine Shulyupin  http://www.makelinux.net/
#
#	Dual BSD/GPL License

RED="\\033[0;31m"
NOCOLOR="\\033[0;39m"
GREEN="\\033[0;32m"
GRAY="\\033[0;37m"

set -o errtrace
tracing=/sys/kernel/debug/tracing
irq=0	# define irq to bind diriver to HW IRQ, WARING: can hung the system
irq=4	# serial port
# irq=`grep ehci_hcd /proc/interrupts | cut -f1 -d:`

tracing()
{
	sudo sh -c "cd $tracing; $1" || true
}

tracing_start()
{
	tracing "echo :mod:ldt > set_ftrace_filter"
	tracing "echo function > current_tracer"
	tracing "echo 1 > function_profile_enabled"
	#sudo cat $tracing/current_tracer
	#sudo cat $tracing/set_ftrace_filter
	#sudo cat $tracing/function_profile_enabled
}

tracing_stop()
{
	( echo Profiling data per CPU
	tracing "cat trace_stat/function*" )> trace_stat.log && echo trace_stat.log saved
	tracing "echo 0 > function_profile_enabled"
	tracing "echo nop > current_tracer"
	sudo cp $tracing/trace ftrace.log && echo ftrace.log saved
}

# sudo rmmod parport_pc parport  ppdev lp
sudo dmesg -n 7
sudo rmmod ldt ldt_plat_dev 2> /dev/null
stty -F /dev/ttyS0 115200
set -o errexit
make -s
data='loopback?'
received=`echo $data | ./dio  --ignore_eof --loops 2 --delay 10 /dev/ttyS0`
if [ "$data" == "$received" ]; then
echo -e "Loopback on /dev/ttyS0 detected"
loopback=0
else
echo -e "No loopback on /dev/ttyS0 detected, running ldt driver with loopback emulation"
loopback=1
fi

sudo insmod ldt.ko loopback=$loopback
sudo insmod ldt_plat_dev.ko

tracing_start || true
# lsmod  | grep ldt
#id=`grep -w ldt /proc/misc | cut -c -3`
. /sys/class/misc/ldt/uevent # get $MAJOR $MINOR
sudo sh -c "rm /dev/ldt;sudo mknod /dev/ldt c $MAJOR $MINOR; chmod o+rw /dev/ldt"
data=123rw
echo $data > /dev/ldt
sleep 0.5
received=`dd iflag=nonblock if=/dev/ldt 2> /dev/null || true`
if [ "$data" == "$received" ]; then
echo -e "${GREEN}LDT nonblocking read/write test passed$NOCOLOR"
else
echo -e "${RED}LDT nonblock read/write test failed$NOCOLOR"
echo expected $data
echo received $received
fi

data=123bl
cat /dev/ldt > R.tmp &
sleep 0.5; echo $data > /dev/ldt;
sleep 0.5
kill %1; wait %1 2> /dev/null || true
received=`cat R.tmp`

if [ "$data" == "$received" ]; then
echo -e "${GREEN}LDT blocking read/write test passed$NOCOLOR"
else
echo -e "${RED}LDT blocking read/write test failed$NOCOLOR"
echo expected $data
echo received $received
fi

data=123mmap
received=`sudo echo $data | ./dio --mmap /dev/ldt`
if [ "$data" == "$received" ]; then
echo -e "${GREEN}LDT mmap test passed$NOCOLOR"
else
echo -e "${RED}LDT mmap test failed$NOCOLOR"
echo expected $data
echo received $received
fi

data=123ioctl
received=`sudo echo $data | ./dio --ioctl /dev/ldt`
if [ "$data" == "$received" ]; then
echo -e "${GREEN}LDT ioctl test passed$NOCOLOR"
else
echo -e "${RED}LDT ioctl test failed$NOCOLOR"
echo expected $data
echo received $received
fi

grep ldt /proc/interrupts || true
tracing_stop || true
sudo dmesg --show-delta --notime --read-clear 2>/dev/null > kernel.log || \
sudo dmesg -c > kernel.log && echo kernel.log saved
